# Generated by Django 4.1.7 on 2023-03-14 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True, max_length=4000)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Galerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dishes')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='the number should have the following format: +380xx xxx xx xx', regex='^\\+?3?8?0?\\d{2}[ -]?(\\d[ -]?){7}$')])),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_response', models.DateTimeField(auto_now=True)),
                ('quests', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_response',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(max_length=4000)),
                ('position', models.CharField(choices=[('M', 'clean environment'), ('E', 'sexpert chefs'), ('F', 'tasty food')], default='M', max_length=2)),
            ],
            options={
                'ordering': ('-position',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=True)),
                ('is_signature', models.BooleanField(default=True)),
                ('is_recomendet', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('ingradients', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='dishes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main_app.dishcategory')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
