# Generated by Django 4.1.7 on 2023-03-15 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='xxxxxx@xxxxxx', regex='^\\w+(_?\\w*)*-?\\w*(_?\\w*)*@\\w+(\\.\\w*)+$')]),
        ),
    ]
